### ISSUE TITLE
Python support

### ISSUE THREAD

**Issue by smari** [aronwoost/sublime-expand-region#11]
Hi! Love the plugin, but unfortunately it doesn't seem to support expansion on Python. It's harder to parse for various reasons (*hangs head*) but it'd be nice to have it anyway... do you think you can add it?

**Comment by jimbo1qaz** [comment]
I hope you're enjoying your 15-month vacation. Where did you visit?

**Comment by r-stein** [comment]
You might give feedback on this pull request https://github.com/aronwoost/sublime-expand-region/pull/53

**Comment by r-stein** [comment]
This has been included in version `v1.3.0` hence I close this PR.
