### ISSUE TITLE
Expansion stopping at non-ascii characters

### ISSUE THREAD

**Issue by antoine-gallix** [aronwoost/sublime-expand-region#32]
Writing some text in french language, which use characters like "é", "à", "ù", "è" or apostrophe, like in l'expansion, I noticed that the expand-region command stops at them. For example when in the word 
élevée, with the cursor placed like this: éle|vée, the expand-region command selects only selects "lev" instead of the whole word. The same happens with a sentence like this one:
"il se rendit compte à l'instant suivant que son voisin l'avait devancé" with the cursor placed like this
"il se rendit compte à l'instant |suivant que son voisin l'avait devancé", expand-region two times in a row selects the folowing region in brackets, stopping at apostrophes (  '  ):
"il se rendit compte à l'[instant suivant que son voisin l]'avait devancé"
I also tried with ü, ï and ë, but in those cases it works fine.

I think the problem could be solved including accented characters (é,à,ù,ç,...) and apostrophes ( ' ) like word characters. Or at least accented characters as apostrophes could also be used around character strings in programming languages, and it would break this good behavior.

I haven't look at the code but I think the author of the code could fix the problem easily.

Cheers!

Antoine

**Comment by r-stein** [comment]
The unicode support is now included `v1.2.2`.

The apostrophe is an other case. Of course it is possible to just add it to the word symbols, but (as you already said) that would yield new problems, because it is used as string delimiter. Feel free to create an issue on the apostrophe problem, but I don't think this will be solved soon =).
