### ISSUE TITLE
Cyrillic in PHP

### ISSUE THREAD

**Issue by Alex-Space** [aronwoost/sublime-expand-region#46]
Hey! Unfortunately this glorious plugin doesn't select cyrillic inside html tags in .php file. But cyrillic in html works fine! That's pretty stange. Is there any solution to fix this?

**Comment by aronwoost** [comment]
It has nothing to do with cyrillic characters. In order to make the HTML expansion work, the file have to have the files extension `.html`. Otherwise the tool can't know, that it should use the html/xml expansion strategy.
