### ISSUE TITLE
Support for pairs of backticks/angle brackets

### ISSUE THREAD

**Issue by wilkystyle** [aronwoost/sublime-expand-region#48]
When editing HTML, I'd like to be able to expand within the angle brackets, for example, if the cursor is where the "href=" text is...

```html
<a href="http://google.com">Go to Google.com</a>
```

... I'd like to be able to expand up to the quotes, including the quotes, and finally, the full text inside the angle brackets: `a href="http://google.com"`

Also, when writing markdown or bash scripts, it would be very helpful to have expansion within a pair of backticks:
```bash
docker rm `docker ps -aq`
```

Maybe there could even be a way for the user to specify their own custom matching pairs of symbols/characters?

**Comment by aronwoost** [comment]
+1 for the backtick pairs.

Re the html expansion: This is already implemented except for the last part ("full text inside the angle brackets"), right?

**Comment by wilkystyle** [comment]
Correct:

* Expand up to the quotes: Works.
* Including the quotes: Works.
* The full text inside the angle brackets: This is what I want.

**Comment by aronwoost** [comment]
May I ask what this would be useful for?

Why would you edit `a href="http://google.com"` when the closing </a> is kept unedited.

**Comment by wilkystyle** [comment]
Aside from the cop-out answer of angle brackets being supported in Emacs' version of `expand region`? :)

One example is when you need to change content or copy/paste content between anything in angle brackets that does not have a closing tag. Say I wanted to take everything from the `img` tag with `newVersion.jpg` and highlight/paste into the `img` tag with `oldVersion.jpg`:

```html
<img src="http://example.com/oldVersion.jpg">

<img src="http://example.com/newVersion.jpg" style="border:1px solid red;">
```

That's a contrived example, but I guess the main point is that I'd like to file away in my brain that, anytime I see text enclosed in angle brackets, I know I can select it using expand-region.

Would it be too hard to allow users to specify arbitrary matching pairs of symbols? This might be more useful than hard-coding specific symbols, and allow for more diverse use cases that we haven't encountered yet.

**Comment by r-stein** [comment]
This is now implemented in version `v1.3.1` and hence I close this PR.

User specifiable symbols does not fit in the design concept at the moment, but this might be possible in the future.

**Comment by wilkystyle** [comment]
Sorry—while the angle brackets are indeed supported, I still don't see support for backticks (the other half of this request) yet... should I pop that into it's own issue?

**Comment by r-stein** [comment]
Yes, that would be nice.
