### ISSUE TITLE
windows sublime2 can not work

### ISSUE THREAD

**Issue by cnweibo** [aronwoost/sublime-expand-region#60]
hi, i have installed your plugin and add the command in the sublime, but nothing happens.
What else i have to do?
My system is windows 10 plus sublime text 2

thanks~!

**Comment by r-stein** [comment]
To clarify your issue:

You have installed the package and added a keybinding to your keymap (e.g. `{ "keys": ["alt+w"], "command": "expand_region" },`). And if you press the keybinding nothing happens?

**Comment by cnweibo** [comment]
sorry, it is the configuration issue. It works perfect after change the keys value(previously, it conflicts with existing one).
Please close this issue.
