### ISSUE TITLE
overrides the "close tab" keyboard shortcut

### ISSUE THREAD

**Issue by ksnyde** [aronwoost/sublime-expand-region#66]
I'm using on the mac and to my surprise this extension seems to override the ⌘w keyboard shortcut which is the default shortcut for closing a tab. I can map it to a key combination I like but it seems to hold onto this mapping and i'm not sure how to block that.

Please help, really like the functionality.

**Comment by aronwoost** [comment]
No, ⌘w is untouched by this extension. Must be some other thing on your side.

**Comment by ksnyde** [comment]
oh @aronwoost sorry I made a silly mistake ... it's the vs-code port of your work. Sorry I clicked on the wrong link.
